### ISSUE TITLE
Design for normal&t

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#1]
A first go at how the two ESCI sheets might be combined to form esci-normal&t

Why did I keep them separate in ESCI?
I had in mind that normal and z scores are mainly used descriptively, with lots of focus on translating between values in original units (X) and corresponding z scores. Hence the second axis in ESCI 'Normal', e.g. for IQ scores.

In contrast, t is mainly used for inference--calculating CIs and (boo!) p values. Of course, z can also be used as a test statistic, so ESCI 'Normal and t' includes both curves, and tail areas for either distribution.

But let's combine the two, and rely on teachers and students to use them for the variety of purposes, esp:
1. exploring and understanding the two curves, and how they relate, for various d.f. values
2. translating between X and z
3. finding tail areas for a given value of the test statistic z or t (one or two tails)
4. finding the critical value of z or t for a given tail area (e.g. .05) (one or two tails)

I expect that the upper axis (X) would be shown for 2., but not usually for the other 3.
_______________________

The challenge for cursor control and tail areas is that we would like to use convenient and conventional round numbers for both 3. and 4. E.g.
Find tail area for z=2, or t(d.f.) = 2
Find z or t(d.f.) for two-tailed area = .05

In ESCI 'Normal and t' it can be slow to shift the cursor(s) to get e.g. tail areas = .05. The slider allows:
1) hold and drag the thumbnail (not sure if it's called that, the darker bar that shifts left and right, in (rough) alignment with one of the cursors.
2) click to left or right of the thumbnail to make it jump a selected medium amount
3) click on an end arrow to shift it by a tiny amount

Back in ESCI 2003, the display changed dynamically as the thumbnail was dragged. But NOT in more recent versions of Excel, alas. And now it's MUCH slower to respond to changes.

One problem is that even the fine jumps of the cursor can mean that we can't find the accurate z or t for a target area (e.g. .01)--we get two values that bracket .01.

So I introduced the 4 values shown at red 5 below the slider as a (rather clumsy) way to get accurate answers to 3. and 4.

A better slider that allowed finer and faster control of the display would be an ideal solution. Ideally, this would allow us to do away with those 4 lower values.

Another less-good option--in addition to a slider to control the cursor(s)--might be to have a drop-down that allowed moving the cursor(s) direct to the position that gives one of a selected number of often-used tail area values. E.g. .2, .1, .05, .025, .01, .005, .001, .0005.

Having this in esci-web is an exciting prospect. No hurry at all.

**Comment by gfmoore** [comment]
So how does this do for starters?

Oh, I think handles, rather than thumbnail ;)

**Comment by gfmoore** [comment]
Can this be closed? Or is there anything here that I've missed?

**Comment by gdcumming** [comment]
0.1.15

Closing. Yay!
