### ISSUE TITLE
Double arrows on sliders

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#10]
In general I love the slider design and behaviour.

Each slider has a double arrow, either just at the R end, or at both ends.

These arrows generally work well, but my instinct is to click and hold on an arrow and expect that, after a brief pause, it will continue changing the value in small steps until I release. I.e. I don’t need to make multiple clicks to shift the value by multiple small steps.

Is providing this click-and-hold behaviour an available option? If so, let’s try it. If not, that’s a pity but no big deal. Don’t go to enormous lengths to try to add it.

If the option is available, let’s have it for all double arrows.

You have chosen the arrows to move the cursors on the big sliders by steps of 0.005. Not a bad choice. If we can have click-and-hold, let’s try steps of 0.001. That would mean we could more often get an accurate critical z (or t) value to match a chosen target tail area.

If we can’t have click-and-hold, let’s try 0.002 steps on the big sliders. That may be too small, but the dragging of the handles is so easy and accurate that such smaller arrow steps may work really well, and be more likely to give us accurate critical z or t values.

**Comment by gfmoore** [comment]
Added code to make these run automatically on mouse down. I can change the speed, it's currently 1 click each 100ms.

The z slider updates now by 0.001

**Comment by gdcumming** [comment]
0.1.12
I love the feel of being able to do a single click, OR a click and hold of a single arrow, and watch the value changing.

I love the small steps, esp. .001 for the big slider.

The trouble is:

1. that when I do a single click on an arrow, most often I get a change of two steps (+/-2 for mu, sigma, df; and +/- .002 for big slider). That's not totally predictable. Try a very fast, light click and sometimes get a change of a single step, sometimes 2. Using the touch pad, more often I get 3 or 4 steps, even for a minimal tap. 

2. that, after trying a bunch of minimal clicks, sometimes the value suddenly starts increasing or decreasing continuously, and all parts of the control are not active. I can't stop the ongoing change. Even changing to the other tab and back doesn't stop the ongoing change of that slider's value. I have to reload. I've had this happen for all the sliders. The ongoing change can be up or down, depending on which arrow I've been using repeatedly. Values can even go negative on the df and mu sliders, for example, even when such values are not accessible with normal slider operation.

Would it be feasible to have a short delay (0.5 sec?) between starting to hold on an arrow and the arrow causing the value to change continuously? Would that solve 2 as well as 1?

**Comment by gdcumming** [comment]
0.1.15

The big sliders and their 'nudge buttons' (nice term!) are a delight to use!
