### ISSUE TITLE
df slider

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#11]
Tab t: The df slider mainly behaves well, not accepting non-numeric typed in values. But type in e.g. 3.3 then use the arrows to reduce the value and it goes negative. The value shown above the slider handle is always sensible—stuck at 1 if the value in the window is negative, and rounded to the nearest integer if value in the window is fractional.

The simplest solution: remove the window reporting the value. The value above the handle is always an integer, min. 1, and (I think) always what corresponds to the displayed t curve—except for one case described below.

Let’s increase the max value to 100, so the slider gives us any integer df value from 1 to 100.

That troublesome case: The double arrows shift the slider handle, and change the value above that handle, but don’t trigger recalculation of the t curve in the display. The curve doesn’t change until the slider handle is dragged.

Ideal would be if the double arrows did trigger curve change, and also were limited to the same range (1-100) as the slider. If that’s hard to achieve, let’s remove the double arrows. That would be OK.

A final tiny point: the small scale underneath the slider has a strange sequence of numbers …21, 26, 30, 35…. And there is a strange choice of two minor tick marks between each two numbered major tick marks. It’s perfectly fine to leave this as is, unless it’s easy to specify something better, maybe values 1, 10, 20, … 80, 90, 100. Even just removing the minor tick marks would be an improvement, but only if easy.

**Comment by gfmoore** [comment]
df minimum equals 1
df max = 100

The scale is problematic. I've set it to allow 0, but programmed it so that it never reaches 0. d3 has really clever algorithms for working out scales, but that cleverness also means that it isn't easy to control. I'll look into seeing if the minimum flag can be set to 1, but the scale will still have to go from 0!!!

**Comment by gdcumming** [comment]
0.1.12
The scale as at present is workable and a perfectly acceptable satisfice. The values in the window now behave well, with typed-in negative numbers 'rounding up' to 1, and high numbers 'rounding down' to 100.

Good fixes: scale is now 1-100, and the arrows are 'live', in the sense that the t curve updates at once.

Playing and thinking further about the sliders, I wonder whether slowing the 'click and hold' on any arrow down to about 4 or 5 per sec would be better. Especially given that the handles can be used so easily and interactively to change values by large, or even fairly small amounts. Would that ease either of the problems I described in comment on #10?

**Comment by gfmoore** [comment]
I've made the left label transparent so doesn't show 0. I don't know how to hack it to make it show 1 - yet.
Sorted out nudge buttons (arrows)

**Comment by gdcumming** [comment]
0.1.15

df slider is a joy to use, no need to fiddle further with the scale
