### ISSUE TITLE
mu and sigma sliders

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#12]
Tab Normal: mu slider: 
Generally behaves well, but typing in e.g. 2.7 gives a rounded value (3) reported above the slider, but the display uses the exact value of 2.7. It’s not good to have two conflicting values displayed, one in the window and one above the handle. Type in something like ‘4xyz’ and see that crazy text in the window but 4 displayed above the handle and used as the value for setting the display.

Tab Normal: sigma slider: 
Generally ok. The slider is limited to 0-100, but the double arrows give us 1 to any positive integer value—just keep clicking past 100. The value displayed in the window governs the positioning of the X axis in the display, so again we can have disagreement between value displayed above the handle (eg 100) and that in the window (eg 104). Type in a negative value and the direction of the displayed X axis reverses.

Simplest solution and probably the best: For both mu and sigma, remove the window displaying a value. Limit the slider (and the double arrows) to integer values:
mu slider: 0 to 200
sigma slider: 1 to 50

(A case could be made for allowing typing in of values, including decimals, to the value windows, but, for the sake of simplicity, I’m happy to live with the limitation to integers and the ranges suggested above.)

See last para of the df slider issue: small numbers and tick marks on the scale below the sliders. If easy, tweak the scale for mu and sigma sliders. But only if easy.
Scale below mu slider: 0, 20, … 200 is fine. Remove minor tick marks?
Scale below sigma slider: Perhaps 1, 10, 20, … 100. Remove minor tick marks?

**Comment by gfmoore** [comment]
Hopefully and with extra programming (well I tried to keep it simple) I think this now works quite well. Added checks on the text box to reject non numeric and force to integer values. I quite like the numeric text boxes and is consistent with dances.
The scales are problematic as built in to the slider and gain I'd have to try and hack the providers code to do anything with it. I've adjusted it as best I can. I can't get rid of minor ticks, can we satisfice for now?

**Comment by gdcumming** [comment]
0.1.15

These two sliders also work beautifully. In addition, the X axis, and the X values on the cursors, all update nicely and quickly, including the little extra tick marks on the axis. Sweet! (A favourite expression of our two sons, always enunciated with their particular style of enthusiastic endorsement.)

**Comment by gdcumming** [comment]
0.1.21

Alas, I spoke too soon!

Tab Normal
mu slider: nudge buttons can take the value above 200 or below 0
sigma slider: nudge button can take the value above 50
sigma slider: when this is set to 1, click in the window showing that value and see a dropdown with values 15, 10, 103, which can be used to change the value

**Comment by gfmoore** [comment]
0.1.22 I think I've covered all bases. Funny that I had in the code for sigma nudge left, but not the others? Probably a cut and past error when sorting out auto nudge.

**Comment by gfmoore** [comment]
The drop down that appears is an autocomplete, funny never noticed that before. There is a bin symbol to delete anything you don't like, or I can look into trying to stop it showing.

**Comment by gdcumming** [comment]
0.1.22

Nudges seem fine, thanks.

I don't follow your comment about the bin symbol, etc, in relation to that autocomplete. Are you suggesting there is some way I could remove it? 

If it's easy to remove it--I don't think the other sliders have anything similar--then that would be good. Else we can easily live with it. A sort of Easter Egg (does software still have these?). I'll close.

**Comment by gfmoore** [comment]
When you use a textbox as you start to fill in a number you get a "dropdown" of suggestions. At the right of the dropdown is a bin symbol to delete the suggestions - well on Microsoft Edge browser anyway.

**Comment by gdcumming** [comment]
If I click in the little value window for the sigma slider, when it shows 1, I get the dropdown but no bin (even when I move mouse down into the dropdown)--that's in my normal Chrome. In Edge I don't get a dropdown.

I played a bit more. In Chrome I get a dropdown (no bin) for df=10--I hadn't noticed that before. In Edge for the df slider at 10 I get a dropdown and a bin--first time I'd seen a bin.

Let's just leave all this. Seems not to be consistent, and hardly intrusive.
