### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#13]
This is a placeholder, with spec for tips to follow resolution of other issues.

**Comment by gdcumming** [comment]
0.1.21

Suggested text for tips: distributions
Style: As for dances:
Font size as now. Boxes tight around text. Tip moves with mouse pointer, within active zone. Same short delay before tip appears.
Active zone for a tip includes both label and the control (radio button, slider, etc)
Let’s try with no tips in large display area on the right

esci logo: font size as now, tighter tip box
esci-web: url
distributions: url
?: Tips on/off, default is off

Tab: Normal Distribution: no tip
1.	Tails: Select features to display
()No tails: No display of tails
()One tail: Each tail can be adjusted separately 
()Two tails: Display two equal-area tails
[]Areas: Display values for areas under the curve

2.	Lines: Click to display lines
[]Mean line: Display the mean line
[]z lines: Display z lines

3.	X variable: X axis can be displayed at top of screen
[]Display X axis: Click to display
Units:[…]: Type a short label for the units of X 
(slider): Select the mean of X, within 0 to 200
(slider): Select the SD of X, within 1 to 50

Tab: Student t Distribution: no tip
4.	Curves: Select curve(s) to display
()z: Display Normal distribution curve 
()t: Display t distribution curve
()z and t: Display both z and t distribution curves 
Degrees of freedom: Select df for t
df(slider): Select df within 1 to 100

5.	Tails: Select features to display
()No tails: No display of tails
()One tail: Each tail can be adjusted separately 
()Two tails: Display two equal-area tails
[]Areas: Display values for areas under the curve

6.	Lines: Click to display lines
[]Mean line: Display the mean line
[]z or t lines: Display z or t lines

Bottom stripe: no tip. Text: Click to return to the New Statistics site

**Comment by gfmoore** [comment]
Done

**Comment by gdcumming** [comment]
0.1.26

Thanks. Generally excellent. A couple of tweaks please, and italics (apologies that I didn't explicitly request these for letters used as symbols). I've only just figured out that I can do Bold and Italic in these comments. Slow learner :-(

**Normal tab**

Edit:
?: Tips on/off, default is off!  <to match dances>

New:
Home: Click to return to esci Home

In italic:
[]z lines: Display _z_ lines

3. _X_ variable: _X_ axis can be displayed at top of screen
(slider): Select the mean of _X_, within 0 to 200
(slider): Select the SD of _X_, within 1 to 50

**Student _t_ tab**

New:
Home: Click to return to esci Home

In Italic:
()_t_: Display _t_ distribution curve
()_z_ and _t_: Display both _z_ and _t_ distribution curves
Degrees of freedom: Select _df_ for _t_
_df_(slider): Select _df_ within 1 to 100

[]_z_ or _t_ lines: Display _z_ or _t_ lines

**Comment by gfmoore** [comment]
No, my fault. I did one of them, but didn't think about the others. Done.

**Comment by gdcumming** [comment]
0.1.28
Looks good, thanks
