### ISSUE TITLE
How the two tabs relate

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#14]
As Bob noted, at present the two tabs relate in strange ways, especially considering selection of no/one/two tabs and display of areas. Make some choices then switch tabs, make some changes, then switch back and find that, often, the selection of radio button ON and Areas checkbox ON/OFF doesn’t match what’s in the display.

There’s also the issue that changing the big slider in one tab often causes the slider in the other tab also to change—even though in the other tab the tail or area might not be displayed.

Bottom line: What we see on the screen at any time needs to be internally consistent. There must be agreement between what is selected in Panels 1 and 2 and what appears in the Tab Normal display. Similarly, we need agreement between Panels 5 and 6 and the Tab t display.

I can see three possible strategies:

1.	Whenever we switch tabs, we see the new tab in a default state. The minimal displays we see when ‘distributions’ is first opened are a reasonable choice for the defaults.

2.	The current states of the two tabs are stored totally separately. When we switch tabs we see the new tab exactly as we last left it. Making a selection, moving a slider, or whatever, makes no change to the other tab.

3.	Yoke the two tabs together, so clicking mu line ON causes that checkbox to be ON, and the line displayed, in both tabs. Etc.

Those three are in my order of preference, 1 being most preferred. Advantages of 1 are that I suspect it might be easy to implement?? Also, it’s predictable and understandable for the user. Also, we can easily advise that if ever you get in a mess, or are trying to shift values back to something familiar, simply switch tabs, then switch back again. Easier to implement than providing a ‘reset’ button, I suspect. Bear in mind also that in practice we are likely to be using just one of the tabs: Tab Normal for descriptives and z scores, in Chapter 4. Or Normal and t for inference, critical values, etc, in Chapter 5. So in practice a user is not likely to be switching often between tabs.

Strategy 1 would mean that the X axis is never displayed in Tab t. That’s fine. (At present it is displayed in both tabs if turned ON in Tab Normal, but in Tab t you can’t turn it off.)

I could live with 2, if that’s easier to do. We advise folks simply to reopen the whole thing if they get in a mess.
I suspect 3 could be tricky to design, build, and understand.

**Comment by gfmoore** [comment]
So nuclear option 1 :) When tab changes everything reset (well I hope, I did test and it looked ok.)
I also made it impossible to select area if no tails and turned off area if no tails reselected

If you want a reset button it will now be easier to implement. I also did some code refactoring, so I might have introduced new errors?

**Comment by gdcumming** [comment]
0.1.12

Nice! Good changes to tails and areas.

One glitch: Switch back to Normal tab, and see 'One tail' rather than 'No tails' selected.

**Comment by gfmoore** [comment]
Ahh that was just some code I left in when testing, saves having to keep selecting, now removed.

**Comment by gdcumming** [comment]
0.1.15

Great
