### ISSUE TITLE
One tail

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#15]
As Bob suggests, when One tail is clicked ON, the L handle and cursor should automatically ‘park’ at -5. Leave the R handle wherever it currently is. This focusses attention on the R handle and cursor and tail area.

Or the user can easily park the R handle at +5 and play with the L handle if they wish to focus on the L tail area.

I love the fact that One tail allows us to move the two handles independently. This makes it easy to find e.g. the area between z=+1 and z=+2, etc. (In ESCI it was often necessary to write down two areas and add or subtract.)

A possible issue is that parking a handle at -5 or +5 doesn’t remove it from play entirely.

For Normal, the L tail area beyond -5 is .0000, so can be ignored. However, for t with 17 or fewer df, the L tail is not zero to 4dp. Even so, the R tail area is still accurate; we just need to note that the ‘central’ area is not totally accurate as (1 – the R tail area), because of that tiny pesky L tail area.

I suggest we live with this, at most making a brief note of it in the textbook.

**Comment by gfmoore** [comment]
Left handle/cursor parked on one tail selected.

Independent handle/cursor. Yes this is why I chose this particular slider as it allows the two handles.

**Comment by gdcumming** [comment]
0.1.18

Good. Feels natural, and will be easy to explain I think.
