### ISSUE TITLE
Strange switching among tail choices

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#16]
In either tab: Choose One tail. Move R cursor. Choose Two tails. Try to move R cursor and see the slider handle move but the cursor remain stationary, release mouse and the handle snaps back to the cursor position. Try again and it all works.

I’m hoping that finalising the other issues causes this glitch to go away!

Occasionally I’ve run across another issue of switching among no/one/two tails. Maybe also switching tabs. Find that trying to drag one of the handles on the big slider doesn’t work—the handle simply won’t move. I haven’t been able to figure out when and why this glitch occurs. Let’s hope this one goes away too!

**Comment by gfmoore** [comment]
I've seen this and I'm looking into it.
The issue of the handles not synchronising when two tails is problematic. This is so far the best I can do. The code for the slider seems to have some kind of timing issue. When you move a cursor it moves 0.001, this then should update the other cursor, but it is so slow that it just doesn't work. The best I have done so far is is to move it at the end of the movement. I might try and move the other cursor perhaps after a full unit has moved by implementing a count. Or maybe I'll realise that I've done something stupid - it's been known. ;)

**Comment by gdcumming** [comment]
0.1.18

1. My first para. Move handle and cursor doesn't move, then handle snaps back. Try again--all ok, both handle and cursor move as they should. But I'm referring to the case following that specific sequence: choose one tail, move R handle+cursor, choose two tails--then get the problem. I'm NOT referring to the general issue that, with two tails, move a handle and the two cursors move smoothly, but the other handle doesn't move, but snaps to the correct position on release of the mouse on the first handle. I don't think this latter issue is a big problem--it's easy to get used to, and the cursors (and tail areas, etc) do move beautifully together. If easy to fix, fine, but don't worry greatly about it. It's the first issue, as I described in my first para, that is weird and remains an issue.

Your comments suggest it may be the second, less serious of the two issues, that is what you are looking in to? Or maybe both.

They are weird. And it's a pity that all the other changes haven't made both of these go away.

2. Last para. This seems to have gone away. Hooray. Touch wood!

**Comment by gfmoore** [comment]
I think I've fixed the snapping issue? 

I've put in a request to the stackoverflow community about the second issue after looking at it most of the day. The issue is that when there's a change I call update which calls the change which ... well you get the idea. I can't figure out a way to stop it, delay it, etc etc. I suspect the resolution will be tricky, if even possible. We'll see :)

**Comment by gfmoore** [comment]
I've tried to stop the overlap when two tailed. I can't actually stop the handles overlapping, but they reset to zero when handle is released. Until I sort out the synchronise issue it's the best I can do.

**Comment by gdcumming** [comment]
0.1.21

I'm very happy with this, and will close. Yes, snapping snafu seems solved, super!

It's good to avoid the overlap, and the handles overlapping and zooming to zero makes sense--that's where the cursors are.

The remaining issue of the other handle not moving until the mouse is released is no big deal--I understand it's irritating from a programming perspective. From a teacher's or student's perspective I think it just doesn't matter very much at all.

**Comment by gdcumming** [comment]
0.1.22

Seems the snapping hasn't gone away totally. Alas.

In either tab, two tail. Areas either on or off. Use right nudge buttons, then drag right handle: this handle moves but its cursor doesn't, then handle snaps back when mouse released. Almost always this happens, sometimes doesn't, especially when only one or two clicks on a R nudge button. Left handle seems fine.

**Comment by gfmoore** [comment]
This issue is proving extremely problematic.

There is some weird stuff going on inside the slider code that is causing real problems with the slide control. The nudging itself is working fine, but the slider controls are causing multiple fires of internal events. At the moment I have no idea how to handle this. The developer does not seem to be responding to queries, so I may have to search for a different slider. Even a query on stackoverflow has seen no response. This issue is related to the same issue that stops the handles working in unison. At the moment the code is broken. Ahh, well something to waste my life on. Can't leave it as is and I've done a lot of refactoring so don't want to go back (yet!).

**Comment by gdcumming** [comment]
Yes, a computer guru's life wasn't meant to be like this...
My own workaround is always to double click on the R handle before dragging it.

**Comment by gfmoore** [comment]
Phew, that was some battle with the dark forces.
After trying about 3 or 4 other sliders I eventually found that the jQuery UI had a slider that didn't go loopy when moving one slider changed the other - infinite loops... However, I then had to search for some library that would provide scales and labels and figure out how that worked. It's not that documentation isn't there, but sometimes it's indecipherable and you spend hours trying out different things and trying to see what tweak does what - yes back to tweaking. At least with video games you get to shoot things (not that I play such games, but I do get it!) 

I think there may well be tweaks you will want me to make and bugs you will find. That's okay, it's to be expected after major surgery... :) 

Let's get this out of the way, then I'll make a start on tooltips. I think we must be pretty close on this app. No outrageous suggestions? What's the next one you need doing?

**Comment by gdcumming** [comment]
0.1.23

That looks very good and seems to solve the wretched snapping issue with the big slider. A few new issues:

1. Either tab, two tail, drag either handle and see both handles, both cursors, and all area values update correctly, I think. But the z or t value on the other handle does not change. Use any nudge and everything updates correctly, I think.

2. Perhaps centre the z/t value (in the moving box) over the handles, rather than offset a bit to the right? Not a big issue.

3. Either tab, one or two tail, move a handle, then make a single click on any nudge button (arrow). Th appropriate handle usually moves by more than one click (more than .001) and often in the wrong direction. That cursor and area value often don't update correctly. Further single nudges work correctly.

4. Move a handle quickly, stop suddenly. The handle moves ahead of the cursor (and tail value), so the handle value and cursor position don't agree. One nudge and the handle moves to the cursor. May not be a big issue.

5. Either tab, one tail. Move a handle, the other cursor and area value shift a bit, but not the other handle, so that other handle and cursor don't agree. Only happens on the first move of a handle.

**Comment by gfmoore** [comment]
0.1.25  2020-08-07  #16 Had to get down and dirty to get values. The official documentation told me how to get values, but these were not correct at the end of the slide (or even really during it.) Eventually discovered another way of getting the actual values. Then I had to directly inject into the DOM for the slider handles to make sure the values displayed as the slide happened. As a certain person said: "The documentation is wrong!".

Also tweaked the label position...eventually. This is because of the new library and I hadn't even noticed that the labels were to the side (I've no idea why as in the examples they were correctly positioned. Same old story, make a tiny change and the fallout is often crazy.

I've tweaked the slider to make it look more like the others a little more. One day I'll probably replace the others, but they do the job for now.

**Comment by gfmoore** [comment]
Oh it's now at 0.1.26

**Comment by gfmoore** [comment]
Oh, by the way, I am aware that I am not getting 3 dp for every slider movement. I honestly don't know how to fix this. I've tried a few things, but they didn't work or worse. It's deep down in the code for the slider and I don't understand it.

I've also noticed that occasionally the sliders jump as they are being dragged especially when the browser window is narrow. I think this too is deep within the slider code and is possibly a timing issue as it moves the other cursor/handle and redraws the display - it is doing this a thousand times for each unit interval! (0.001 steps)

**Comment by gdcumming** [comment]
0.1.28

I haven't been able to observe the two problems you mention (not getting 3dp, sliders jump).

I think you have solved all 5 issues I described, which is fabulous. It feels very fast and responsive and accurate. A joy to use.

Only one tiny issue: The two handles (and the values above them) are both displaced a little to the right, in relation to the small scale immediately under the slider, and the main X axis. Displaced by about half the radius of the handle. If it's a problem to tweak this, we can happily satisfice.

**Comment by gfmoore** [comment]
Well, that's another weird one. I've tweaked and I think everything lines up, yet if you move the left slider inwards then you can see that the left slider track endpoint is not going to where you expect, but the slider at that point looks fine.

I think it might just have to be something we live with. I think, it's a consequence of making the handles bigger and so it has affected the internal calculations for the slider width. Everything has an unintended consequence.

I guess there must be a slider widget out there that does everything we want it to, but I can't find it, not even a paid for version.

**Comment by gdcumming** [comment]
0.1.29

To my eye it lines up well.

I'm not sure what you mean by the 'left slider track endpoint...'. The only tiny issue I can see is that if you click on either handle and very carefully move it a tiny bit left or right, the handle, cursor (and the values) all make a little jump right. Then move left (right) if you keep dragging left (right). In normal use, a user may or may not notice a small hiccup at the start of a click and drag of either handle.

This is a joy to use. I'm going to close.

**Comment by gfmoore** [comment]
Oops I meant right. Its the end of the sliding track. It's shorter than you might expect. Its just a visual thing.

⁣Regards,

Gordon Moore
gm@gordonmoore.co.uk​

**Comment by gdcumming** [comment]
I see (just!) what you mean. Even less of an issue than the hiccup. Definitely not to worry!
