### ISSUE TITLE
Inconsistency in panel orderings.

### ISSUE THREAD

**Issue by gfmoore** [gfmoore/esci-distributions#18]
I have noticed an inconsistency in the panel ordering between the Normal tab and the Normal/Student t tab.

Tail and Lines are in the correct order, but come first before the yellow X panel whereas in the Student t panel they come after the yellow df panel. 

Or change the colour of one of the panels?

**Comment by gdcumming** [comment]
0.1.15

Good point.

Thinking back, I believe the ordering, and colours, strategy I used was based on how I thought I'd use the Normal, and Normal and t, in the classroom, and discuss them in the book. These have become the two tabs, and I think the same considerations apply.

First, I'd be using the two rather separately, at least at first. So the Normal tab is in Chap 4 (Sampling and Normal Dist), but t dist tab is in Chap 5 (CIs). Using Norm Dist tab, I'd start with the distribution, consider tails, areas, and then z lines. Then introduce the X axis and transformations between z and X. So the order of panels in the Normal tab fit with that sequence.

Moving on to the t tab (and Ch 5), I'd move on from Normal to t and talk about df and the varying shape of t curves, and comparison with Normal shape. Then tails and areas, then z lines. Again, the order of panels is intended to fit this sequence.

Colours: I kept them consistent for the tails+areas, and the display-lines. Yellow was simply used for the 'other' panel in each case. I guess it would be logical to have those two 'other' panels different colours, We could have Panel 4 a different colour, say pale red or pale green--or something else convenient?

**Comment by gfmoore** [comment]
Palegreen it is, looks better :)

**Comment by gdcumming** [comment]
0.1.18

Thanks, not bad. At risk of being a pain again, do you have a paler green we could have a squiz at?

**Comment by gfmoore** [comment]
Is this better? ;)

**Comment by gdcumming** [comment]
0.1.19

Yep, good, thanks, let's close
