### ISSUE TITLE
Lower part of curves hidden

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#19]
0.1.23

The display size generally adjusts well for different screen sizes.

But, in the course of making figures for the book I've discovered on glitch. Click top right (far top right corner, next to 'X') to switch from maximise (to fit screen) down to 'Restore down'. 'distributions' adjusts to fit the smaller window. The LH display area (control panel) fits well, the big slider and curve(s) in the RH display fit well, EXCEPT that the area values on the figure can be hidden below the z/t axis. Drag the bottom edge of the window down and the area values progressively appear. With luck, they will all appear by the time we reach the bottom of the screen. The curve itself adjusts correctly as the bottom edge of the window is dragged down; just the area values seem to be set assuming the display area is the full height of the physical screen, so are hidden unless the display area is close to the full height of the screen.

This arose because I needed to shift the right window edge in, to make a figure with good proportions for a book page. I noticed that the tail area values were sitting right on the z/t axis. I needed to drag the bottom edge of the window down as far as I could to get those area values up a bit from that axis.

I suspect that, for most users in practice, this probably wouldn't matter much. If not easy to fix, we could leave it, in the holy name of 'satisfice'!

**Comment by gfmoore** [comment]
Well I certainly observed this. I looked at layout code, did a bit of waving of hands and spoke dark incantations and it's not happening now, but to be honest I'm not really sure what I did to fix it, if indeed I did :( 
0.1.26 (along with slight tweaks to slider appearance.

**Comment by gdcumming** [comment]
0.1.28

All seems to work well for me, which is great.
