### ISSUE TITLE
Height of verticals in displays

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#4]
In Tab Normal, let’s have the cursors at tail boundaries extend up to the X axis, whether or not that axis is displayed. Just as the mu line and z lines currently do.
In Tab t, let’s have the cursors at tail boundaries extend up as high as the mu line and z lines currently extend.

**Comment by gfmoore** [comment]
I'm not sure what you meant by this? What "cursors at tail boundaries" were you referring to. Assuming you meant the actual critical lines I extended these. But these can be anywhere not just at tail boundaries. It's easy enough to revert if I misunderstood.

**Comment by gdcumming** [comment]
Perfect, thanks
