### ISSUE TITLE
Tick marks on axes

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#5]
Can we have minor tick marks on all axes in both displays? Perhaps ideally 9 between each major tick mark (with number), thus dividing each interval into 10. Or 4, dividing each interval into 5.

**Comment by gfmoore** [comment]
Wow this wasn't as easy as I thought it would be. d3 is very clever in doing the axes, but there's no option for adding minor ticks, so I had to do it manually. How does it look?

**Comment by gdcumming** [comment]
It looks terrific
