### ISSUE TITLE
Display X values for cursors in display

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#7]
Tab Normal: When X axis is displayed and One or Two tails is ON, display ‘X=xxx’ near the top of each cursor, maybe just lower than the ‘IQ score’ label on X axis. The ‘xxx’ is the cursor position on the X axis. (X to be italic in those reports of value.)

**Comment by gfmoore** [comment]
Okay, so I've had a go, but not sure if this looks good with the cursor extending all the way? I  created a white borderless rectangle behind the text? The problem is that when just below the label of IQ score it cuts through the top of the curve.

I'm sure you'll think of a better position... lol

**Comment by gdcumming** [comment]
0.1.12
It's what I asked for, and it looks pretty good. I like the borderless rectangles of white, and the fact that the curve is in front of everything, so we always see it.

When I try to adjust the two-tail case to get the area from 99.5 to 100.5 (an exercise in the book), then the overlap of values is an issue.

Could we try having:
1. The rectangles just outboard of the cursors? So just left of the left cursor, just right of the right cursor, as we have for the tail area values. 
2. 'X =' on the line where the current rectangle is positioned (just below the 'IQ Points' label), and the value of X in a rectangle immediately below. 

I think 1. would definitely be better. I'm not sure about 2. If easy, give it a try? What do you think? If too much trouble, let's go with just 1.

**Comment by gfmoore** [comment]
I've implemented 1, but it was a tight fit and I had to slightly reduce the font size, but I don't think you'd have noticed. I also dropped the height below the top axis slightly so that it looked better when sliding over the curve.

**Comment by gdcumming** [comment]
0.1.15

It looks good and behaves well. What a team!

I actually like the slightly smaller font. I'd been thinking that all the values for areas would be better in a slightly smaller font. But I was trying to moderate the extent of my outrageous requests. (You may not have noticed!) But, if not too difficult, could we have all those area values in this same slightly smaller font?

**Comment by gfmoore** [comment]
Done

**Comment by gdcumming** [comment]
0.1.18

Great, thanks
